baseURL = '/'
theme = 'PaperMod'
languageCode = 'cn'
DefaultContentLanguage = 'cn'

enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = false
