[en]
  weight = 2
  baseURL = '/'
  languageCode = "en"
  languageName = 'English'
  title = 'Binary WareHouse'
[zh-cn]
  weight = 1
  baseURL = '/'
  languageCode = "zh-CN"
  languageName = '简体中文'
  title = '二进制仓库'
