[[main]]
  weight = 1
  identifier = "Search"
  name = "搜索"
  url = "/search"
[[main]]
  weight = 2
  identifier = "posts"
  pre = ""
  post = ""
  name = "日志"
  url = "/posts/"
  title = "Posts"
[[main]]
  weight = 3
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = "Tags"
[[main]]
  weight = 4
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = "Categories"
