[[main]]
  weight = 1
  identifier = "Search"
  name = "搜索"
  url = "/search"
[[main]]
  weight = 2
  identifier = "Bookmark"
  name = "书签"
  url = "https://bookmarks.binwh.com/"
[[main]]
  weight = 3
  identifier = "Appmark"
  name = "应用"
  url = "/appmark"
[[main]]
  weight = 4
  identifier = "posts"
  pre = ""
  post = ""
  name = "日志"
  url = "/posts/"
  title = "Posts"
[[main]]
  weight = 5
  identifier = "wiki"
  pre = ""
  post = ""
  name = "百科"
  url = "/wiki"
[[main]]
  weight = 6
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = "Tags"
[[main]]
  weight = 7
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = "Categories"
[[main]]
  weight = 8
  identifier = "about"
  name = "关于"
  url = "/about"
