[[main]]
  weight = 0
  identifier = "Search"
  name = "Search"
  url = "/search"
[[main]]
  weight = 1
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
[[main]]
  weight = 2
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
[[main]]
  weight = 3
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
