[[main]]
  weight = 1
  identifier = "Search"
  name = "Search"
  url = "/search"
[[main]]
  weight = 2
  identifier = "Bookmark"
  name = "Navigation"
  url = "https://nav.binwh.com/"
[[main]]
  weight = 3
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
[[main]]
  weight = 10
  identifier = "about"
  name = "About"
  url = "/about"
