[[main]]
  weight = 1
  identifier = "Search"
  name = "搜索"
  url = "/search"
[[main]]
  weight = 2
  identifier = "Bookmark"
  name = "导航"
  url = "https://nav.binwh.com/"
[[main]]
  weight = 3
  identifier = "Appmark"
  name = "应用"
  url = "/appmark"
[[main]]
  weight = 4
  identifier = "posts"
  pre = ""
  post = ""
  name = "日志"
  url = "/posts/"
  title = "Posts"
[[main]]
  weight = 10
  identifier = "about"
  name = "关于"
  url = "/about"
