ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

ShareButtons = ["x", "facebook", "telegram", "reddit"]

[assets]
  favicon = "img/favicon.ico"
  favicon16x16 = "img/bin2.gif"
  favicon32x32 = "img/bin1.gif"
  apple_touch_icon = "img/bin1.gif"
  safari_pinned_tab = "img/bin1.gif"

[label]
  icon = "img/bin2.gif"
  iconHeight = 32

# for search
# https://fusejs.io/api/options.html
[fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  # limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
  keys = [ "title", "permalink", "summary", "content" ]

pygmentsUseClasses = true

[markup]
  [highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = monokai

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
