defaultTheme = 'auto'
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

ShareButtons = ["x", "facebook", "telegram", "reddit"]

[assets]
  favicon = "img/favicon.ico"
  favicon16x16 = "img/bin2.gif"
  favicon32x32 = "img/bin1.gif"
  apple_touch_icon = "img/bin1.gif"
  safari_pinned_tab = "img/bin1.gif"

[label]
  icon = "img/bin2.gif"
  iconHeight = 32

# for search
# https://fusejs.io/api/options.html
[fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  # limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
  keys = [ "title", "permalink", "summary", "content" ]

pygmentsUseClasses = true

[markup]
  #[goldmark]
  #  [renderer]
  #      unsafe = true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  [highlight]
    # noClasses：使用 class 标签，而不是内嵌的内联样式
    # noClasses = false
    # anchorLineNos = true
    # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
    codeFences = true
    # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
    guessSyntax = true
    # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
    # lineNoStart：行号从编号几开始，一般从 1 开始。
    # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
    # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
    lineNos = true
    style = 'monokai'

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[params.page.comment]
  enable = true
  [params.page.comment.giscus]
    # 你可以参考官方文档来使用下列配置
    enable = true
    repo = "wenhq/binwh.blog"
    repoId = "MDEwOlJlcG9zaXRvcnkyMzM1Mzk1MTk="
    category = "Announcements"
    categoryId = "DIC_kwDODeuHv84Cc-iS"
    # 为空时自动适配当前主题 i18n 配置
    lang = ""
    mapping = "pathname"
    # <your_mapping> 对应官网的 data-mapping
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lazyLoading = false
    lightTheme = "light"
    darkTheme = "dark_dimmed"
    #theme = "preferred_color_scheme"
    #crossorigin="anonymous"
