baseURL = 'https://binwh.com/'
paginate = 10
theme = 'PaperMod'

defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Binary WareHouse"
    weight = 1
  [languages.cn]
    title = "二进制仓库"
    weight = 2

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

#googleAnalytics: ""

DefaultContentLanguage = 'zh-CN'

[minify]
  disableXML = true
  minifyOutput = true

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:slug/'
    tutorials = '/training/:slug/'
  [permalinks.section]
    posts = '/articles/'
    tutorials = '/training/'

[params]
  # defaultTheme = light
  # defaultTheme = dark
  # to switch between dark or light according to browser theme
  defaultTheme = "auto"
