baseURL = 'https://binwh.com/'
languageCode = 'en-us'
title = 'Binary WareHouse'
paginate = 10
theme = 'PaperMod'

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:slug/'
    tutorials = '/training/:slug/'
  [permalinks.section]
    posts = '/articles/'
    tutorials = '/training/'
